import Head from "next/head";
import HomeIntro from "../components/HomeIntro";
import Services from "../components/Services";
import styles from "../styles/Home.module.css";
import { data, users } from "../data";
import Testimonials from "../components/Testimonials";

const index = ({ services, testimonials }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>AVOCADO AGENCY NEXT-JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeIntro />
      <Services services={services} />
      <Testimonials users={testimonials} />
    </div>
  );
};

export default index;

export const getStaticProps = async () => {
  const services = data;
  const testimonials = users;

  return {
    props: {
      services,
      testimonials,
    },
  };
};
